/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apkkasir_rera;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author OWNER
 */
public class home extends javax.swing.JFrame {
        Connection konek;
        PreparedStatement pst;
        ResultSet rst;

    /**
     * Creates new form home
     */
 public home() {
       initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        konek = koneksi.koneksiDB();
        mulai();
        tampilWaktu();
    }
 public void mulai() {
    formlogin.setVisible(false);
    register.setEnabled(false);
    logout.setEnabled(false);
    master.setEnabled(false);
    transaction.setEnabled(false);
    recaplaporan.setEnabled(false);
    txttime.setEnabled(false);
    txtdate.setEnabled(false);
    btnregister.setEnabled(false);
    btnproduct.setEnabled(false);
    btncustomer.setEnabled(false);
    btnsale.setEnabled(false);
}
    
    public void tampilWaktu() {
        Thread clock = new Thread() {
            public void run() {
                for(;;) {
                    Calendar cal = Calendar.getInstance();
                    SimpleDateFormat Jam = new SimpleDateFormat("HH:mm:ss");
                    SimpleDateFormat Tanggal = new SimpleDateFormat("yyyy-MM-dd");
                    txttime.setText(Jam.format(cal.getTime()));
                    txtdate.setText(Tanggal.format(cal.getTime()));
               try { sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(menuutama.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
            }
        };
        clock.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnregister = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnsale = new javax.swing.JButton();
        btnproduct = new javax.swing.JButton();
        btncustomer = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        formlogin = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        acces = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        cmbacces = new javax.swing.JComboBox<>();
        btncancel = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        register = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        customer = new javax.swing.JMenuItem();
        product = new javax.swing.JMenuItem();
        transaction = new javax.swing.JMenu();
        sale = new javax.swing.JMenuItem();
        recaplaporan = new javax.swing.JMenu();
        recaplp = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        btnregister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-form-30 (1).png"))); // NOI18N
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbluser.setText("Login Disini");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnregister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbluser)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(btnregister)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        btnsale.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnsale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-sale-20.png"))); // NOI18N
        btnsale.setText("Sale");
        btnsale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaleActionPerformed(evt);
            }
        });

        btnproduct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-product-30 (1).png"))); // NOI18N
        btnproduct.setText("Product");
        btnproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductActionPerformed(evt);
            }
        });

        btncustomer.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btncustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-20.png"))); // NOI18N
        btncustomer.setText("Customer");
        btncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btncustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnproduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsale)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsale, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnproduct)
                    .addComponent(btncustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 479, -1, -1));
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 11, 46, -1));

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        getContentPane().add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 11, 45, -1));

        formlogin.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-circled-user-female-skin-type-6-30.png"))); // NOI18N
        jLabel4.setText("FORM LOGIN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(29, 29, 29))
        );

        username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        username.setText("Username");

        password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        password.setText("Password");

        acces.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acces.setText("Acces Rights");

        cmbacces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select One-", "Admin", "Officer" }));
        cmbacces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbaccesActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-list-20.png"))); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-login-20.png"))); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formloginLayout = new javax.swing.GroupLayout(formlogin.getContentPane());
        formlogin.getContentPane().setLayout(formloginLayout);
        formloginLayout.setHorizontalGroup(
            formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(formloginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acces)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addGap(28, 28, 28)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtusername)
                    .addComponent(cmbacces, 0, 223, Short.MAX_VALUE)
                    .addComponent(txtpassword))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(formloginLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btncancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnlogin)
                .addGap(99, 99, 99))
        );
        formloginLayout.setVerticalGroup(
            formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formloginLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formloginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(username))
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formloginLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(password))
                    .addGroup(formloginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formloginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(acces))
                    .addComponent(cmbacces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(formloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnlogin))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(formlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 50, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-20 (1).png"))); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        home.add(login);

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        home.add(register);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        home.add(logout);

        jMenuBar1.add(home);

        master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-master-20.png"))); // NOI18N
        master.setText("Master");

        customer.setText("Customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        master.add(customer);

        product.setText("Product");
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        master.add(product);

        jMenuBar1.add(master);

        transaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-transaction-list-30.png"))); // NOI18N
        transaction.setText("Transaction");

        sale.setText("Sale");
        sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionPerformed(evt);
            }
        });
        transaction.add(sale);

        jMenuBar1.add(transaction);

        recaplaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-report-20.png"))); // NOI18N
        recaplaporan.setText("Report");
        recaplaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recaplaporanActionPerformed(evt);
            }
        });

        recaplp.setText("Recap Report");
        recaplp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recaplpActionPerformed(evt);
            }
        });
        recaplaporan.add(recaplp);

        jMenuBar1.add(recaplaporan);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-about-20.png"))); // NOI18N
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        help.add(jMenuItem1);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        new formregister().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnsaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaleActionPerformed
        new formpenjualan().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btnsaleActionPerformed

    private void btnproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductActionPerformed
        new formproduk().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btnproductActionPerformed

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed
        new formpelanggan().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btncustomerActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void cmbaccesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbaccesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbaccesActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        new menuutama().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        try {
            String sql="select * from login where Username='"+txtusername.getText()+"' and Password='"+txtpassword.getText()+"' and HakAkses='"+cmbacces.getSelectedItem()+"'";
            pst = konek.prepareStatement(sql);
            rst = pst.executeQuery();
            if (rst.next()) {
                if(txtusername.getText().equals(rst.getString("Username"))&& txtpassword.getText().equals(rst.getString("Password"))&& cmbacces.getSelectedItem().equals(rst.getString("HakAkses")))
                if(cmbacces.getSelectedItem().equals("Admin")){
                    register.setEnabled(true);
                    logout.setEnabled(true);
                    master.setEnabled(true);
                    transaction.setEnabled(true);
                    recaplp.setEnabled(true);
                    formlogin.setVisible(false);
                    btnregister.setEnabled(true);
                    btnproduct.setEnabled(true);
                    btncustomer.setEnabled(true);
                    btnsale.setEnabled(true);
                    txttime.setEnabled(false);
                    txtdate.setEnabled(false);
                } else if(cmbacces.getSelectedItem().equals("Officer")){
                    register.setEnabled(false);
                    logout.setEnabled(true);
                    master.setEnabled(true);
                    transaction.setEnabled(true);
                    recaplp.setEnabled(true);
                    formlogin.setVisible(false);
                    btnregister.setEnabled(false);
                    btnproduct.setEnabled(true);
                    btncustomer.setEnabled(true);
                    btnsale.setEnabled(true);
                    txttime.setEnabled(false);
                    txtdate.setEnabled(false);
                }

                {
                    JOptionPane.showMessageDialog(null, "Selamat Datang '"+txtusername.getText()+"'");
                    String text = txtusername.getText();
                    lbluser.setText(text);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Login. Periksa kembali Username, Password dan Hak Akses");
                txtusername.setText("");
                txtpassword.setText("");
                cmbacces.setSelectedItem("-Select One-");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        formlogin.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        new formregister().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new menuutama().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        new formpelanggan().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        new formproduk().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionPerformed
        new formpenjualan().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_saleActionPerformed

    private void recaplpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recaplpActionPerformed
        new formlaptransaksi().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_recaplpActionPerformed

    private void recaplaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recaplaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recaplaporanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new formabout().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acces;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncustomer;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnproduct;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnsale;
    private javax.swing.JComboBox<String> cmbacces;
    private javax.swing.JMenuItem customer;
    private javax.swing.JInternalFrame formlogin;
    private javax.swing.JMenu help;
    private javax.swing.JMenu home;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbluser;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu master;
    private javax.swing.JLabel password;
    private javax.swing.JMenuItem product;
    private javax.swing.JMenu recaplaporan;
    private javax.swing.JMenuItem recaplp;
    private javax.swing.JMenuItem register;
    private javax.swing.JMenuItem sale;
    private javax.swing.JMenu transaction;
    private javax.swing.JTextField txtdate;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
